name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to the runner
      - name: Check out the repository
        uses: actions/checkout@v2

      # Copy requirements.txt to the server
      - name: Copy requirements.txt to the server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./requirements.txt"
          target: "/home/forge/streamlit/"

      # Install dependencies globally without sudo
      - name: Install dependencies on the server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            pip3 install --upgrade pip
            pip3 install -r /home/forge/streamlit/requirements.txt
            pip3 install google-cloud-bigquery

      # Pull the latest changes from the repository
      - name: pushing changes to wideright.app server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/forge/streamlit
            git pull origin main

      # Restart Streamlit and clear cache
      - name: restarting streamlit and clearing cache
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            supervisorctl restart streamlit
            streamlit cache clear
