name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to the runner
      - name: Check out the repository
        uses: actions/checkout@v2

      # Copy requirements.txt to the server
      - name: Copy requirements.txt to the server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./requirements.txt"
          target: "/home/forge/streamlit/"

      # Install python3-venv package on the server
      - name: Install python3-venv on the server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: sudo apt-get update && sudo apt-get install -y python3-venv

      # SSH into the server and deploy the application
      - name: pushing changes to wideright.app server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/forge/streamlit
            git pull origin main
            # Create a virtual environment
            python3 -m venv venv
            # Activate the virtual environment
            source venv/bin/activate
            # Upgrade pip to the latest version
            pip install --upgrade pip
            # Install dependencies from requirements.txt
            pip install -r requirements.txt
            # Explicitly install google-cloud-bigquery (for troubleshooting)
            pip install google-cloud-bigquery
            # List installed packages to verify installation
            pip freeze

      # Restart Streamlit and clear cache
      - name: restarting streamlit and clearing cache
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            source /home/forge/streamlit/venv/bin/activate
            sudo supervisorctl restart streamlit
            streamlit cache clear
