name: Run mfl_players pipeline from players.py
on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight every day
  workflow_dispatch: null
env:
  DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: mfl-374514
  DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: mfl-orchestrator@mfl-374514.iam.gserviceaccount.com
  DESTINATION__BIGQUERY__LOCATION: US
  API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
  DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY }}

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.x
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements_github_action.txt
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: pip install -r requirements_github_action.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Run players script
        run: python 'dlt/players.py'
      - name: Run draft picks script
        run: python 'dlt/draft_picks.py'
      - name: Run league script
        run: python 'dlt/league.py'
      - name: Run rosters script
        run: python 'dlt/rosters.py'
      - name: Run assets script
        run: python 'dlt/assets.py'
      - name: Run schedule script
        run: python 'dlt/schedule.py'
