name: Run dlt pipelines
on:
  schedule:
    - cron: '0 6 * * *'  # Run at 6 AM every day
  workflow_dispatch: null
env:
  DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: mfl-374514
  DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: mfl-orchestrator@mfl-374514.iam.gserviceaccount.com
  DESTINATION__BIGQUERY__LOCATION: US
  MFL_API_KEY: ${{ secrets.MFL_API_KEY }}
  MFL_USER_ID: ${{ secrets.MFL_USER_ID }}  # <-- ADD THIS LINE
  DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY }}

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.x
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements_github_action.txt
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: pip install -r requirements_github_action.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Check DLT Environment Variables
        run: |
          echo "--- Checking DLT Environment Variables ---"
          echo "MFL_API_KEY is set: ${{ env.MFL_API_KEY != '' }}"

          echo "--- General BigQuery Destination Credentials (from workflow env block) ---"
          echo "DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID (hardcoded): $DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID"
          echo "DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL (hardcoded): $DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL"
          echo "DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY is set: ${{ env.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY != '' }}"
          echo "DESTINATION__BIGQUERY__LOCATION (hardcoded): $DESTINATION__BIGQUERY__LOCATION"

          echo "--- Pipeline-Specific Checks (Example: mfl_assets) ---"
          echo "MFL_ASSETS__DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID is set: ${{ env.MFL_ASSETS__DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID != '' }}"
          echo "MFL_ASSETS__DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL is set: ${{ env.MFL_ASSETS__DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL != '' }}"
          echo "MFL_ASSETS__DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY is set: ${{ env.MFL_ASSETS__DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY != '' }}"

          echo "--- Pipeline-Specific Checks (Example: mfl_players) ---"
          echo "MFL_PLAYERS__DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID is set: ${{ env.MFL_PLAYERS__DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID != '' }}"
          echo "MFL_PLAYERS__DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL is set: ${{ env.MFL_PLAYERS__DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL != '' }}"
          echo "MFL_PLAYERS__DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY is set: ${{ env.MFL_PLAYERS__DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY != '' }}"

          echo "--- Checking GOOGLE_APPLICATION_CREDENTIALS (set by google-github-actions/auth) ---"
          echo "GOOGLE_APPLICATION_CREDENTIALS is set: ${{ env.GOOGLE_APPLICATION_CREDENTIALS != '' }}"
          if [[ "${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" != "" ]]; then
            echo "GOOGLE_APPLICATION_CREDENTIALS value: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          fi
          echo "--- End DLT Environment Variable Check ---"

      # - name: Run players script
      #   run: python -m dlt_scripts.players
      - name: Run draft picks script
        run: python -m dlt_scripts.draft_picks
      # - name: Run league script
      #   run: python -m dlt_scripts.league
      - name: Run rosters script
        run: python -m dlt_scripts.rosters
      - name: Run assets script
        run: python -m dlt_scripts.assets
      - name: Run schedule script
        run: python -m dlt_scripts.schedule
      # - name: Run scores script
      #   run: python -m dlt_scripts.scores
      # - name: Run standings script
      #   run: python -m dlt_scripts.standings
      # - name: Run results script
      #   run: python -m dlt_scripts.results
      # - name: Run Last Yr Rosters script
      #   run: python -m dlt_scripts.last_yr_rosters
      # - name: Run Last Yr Players script
      #   run: python -m dlt_scripts.last_yr_players
      # - name: Run Last Yr Scores script
      #   run: python -m dlt_scripts.last_yr_scores