name: Run mfl_players pipeline from players.py

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch: null

env:
  DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: mfl-374514
  DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: mfl-orchestrator@mfl-374514.iam.gserviceaccount.com
  DESTINATION__BIGQUERY__LOCATION: US
  API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}

jobs:
  maybe_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: always
          skip_after_successful_duplicate: 'false'
          do_not_skip: '[]'

  run_pipeline:
    needs: maybe_skip
    if: needs.maybe_skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Install dependencies
        run: pip install -r requirements_github_action.txt

      - name: Configure GCP Credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcp_credentials.json

          # Validate JSON file before proceeding
          if ! jq empty $HOME/gcp_credentials.json; then
            echo "Invalid JSON format in GCP_CREDENTIALS"
            exit 1
          fi

          # Save private_key from secrets to a file without newlines
          echo "${{ secrets.GCP_PRIVATE_KEY }}" | tr -d '\n' > $HOME/private_key.txt

          # Insert private_key into JSON using jq
          jq --arg key "$(cat $HOME/private_key.txt)" '.private_key = $key' $HOME/gcp_credentials.json > $HOME/gcp_credentials_final.json
          
          # Validate modified JSON file
          if ! jq empty $HOME/gcp_credentials_final.json; then
            echo "Invalid JSON format after inserting private_key"
            exit 1
          fi
          
          mv $HOME/gcp_credentials_final.json $HOME/gcp_credentials.json

          echo "Content of gcp_credentials.json after modification:"
          cat $HOME/gcp_credentials.json

      - name: Set environment variables
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp_credentials.json" >> $GITHUB_ENV

      - name: Debug GCP Credentials
        run: cat $HOME/gcp_credentials.json

      - name: Run pipeline script
        run: python 'players.py'
