name: Run mfl_players pipeline from players.py
'on':
  schedule:
  - cron: '*/30 * * * *'
  workflow_dispatch: null
env:
  DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: mfl-374514
  DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: mfl-orchestrator@mfl-374514.iam.gserviceaccount.com
  DESTINATION__BIGQUERY__LOCATION: US
  API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
  DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY }}
  TESTING: 1234\n1234
  TESTING2: 1234\\n1234
jobs:
  maybe_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: always
        skip_after_successful_duplicate: 'false'
        do_not_skip: '[]'
  run_pipeline:
    needs: maybe_skip
    if: needs.maybe_skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.x
    - name: Install Requirements
      run: pip install -r requirements_github_action.txt
    - name: Debug environment
      run: |
        echo "Project ID: $DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID"
        echo "Client Email: $DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL"
        echo "Private Key: $DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY"
        echo "Nonexistent: $AAAAA"
        echo "Testing: $TESTING"
        echo "Testing 2: $TESTING2"
    - name: Run pipeline script
      run: python 'players.py'
      env:
        DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: mfl-374514
        DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: mfl-orchestrator@mfl-374514.iam.gserviceaccount.com
        DESTINATION__BIGQUERY__LOCATION: US
        API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY }}
