name: Run dlt pipelines
on:
  schedule:
    - cron: '0 6 * * *'  # Run at 6 AM every day
  workflow_dispatch: null
env:
  DESTINATION__BIGQUERY__CREDENTIALS__PROJECT_ID: mfl-374514
  DESTINATION__BIGQUERY__CREDENTIALS__CLIENT_EMAIL: mfl-orchestrator@mfl-374514.iam.gserviceaccount.com
  DESTINATION__BIGQUERY__LOCATION: US
  API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
  DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY: ${{ secrets.DESTINATION__BIGQUERY__CREDENTIALS__PRIVATE_KEY }}

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.x
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements_github_action.txt
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: pip install -r requirements_github_action.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      # - name: Run players script
      #   run: python -m dlt.players
      - name: Run draft picks script
        run: python -m dlt.draft_picks
      # - name: Run league script
      #   run: python -m dlt.league
      # - name: Run rosters script
      #   run: python -m dlt.rosters
      - name: Run assets script
        run: python -m dlt.assets
      # - name: Run schedule script
      #   run: python -m dlt.schedule
      # - name: Run scores script
      #   run: python -m dlt.scores
      # - name: Run standings script
      #   run: python -m dlt.standings
      # - name: Run results script
      #   run: python -m dlt.results
