name: Upgrade Streamlit
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: Deploy and Upgrade
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Remove the old system-level package to resolve path conflict
            sudo rm -rf /usr/local/lib/python3.8/dist-packages/typing_extensions*
            cd /home/forge/streamlit
            git pull
            pip3 install --upgrade pip
            pip3 install --no-cache-dir -r requirements.txt
            sudo supervisorctl restart streamlit
            streamlit cache clear
